lib/cookie_auth_web/router.ex
defmodule CookieAuthWeb.Router do
  use CookieAuthWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :check_auth do
    plug :auth_verify
  end

  pipeline :req_auth do
    plug :require_auth
  end

  pipeline :req_no_auth do
    plug :require_no_auth
  end

  def require_no_auth(conn, _params) do
    if CookieAuth.Accounts.user_signed_in?(conn) do
      conn
      |> put_flash(:error, "require not auth")
      |> redirect(to: "/")
    else
      conn
    end
  end

  def require_auth(conn, _params) do
    if CookieAuth.Accounts.user_signed_in?(conn) do
      conn
    else
      conn
      |> put_flash(:error, "require auth")
      |> redirect(to: "/")
    end
  end

  def auth_verify(conn, _params) do
    case CookieAuth.Accounts.verify_auth(conn) do
      {:ok, user} ->
        conn
        |> assign(:current_user, user)
        |> assign(:user_signed_in, true)
      {:error, :invalid_token} ->
        conn
        |> CookieAuth.Accounts.logout()
        |> assign(:user_signed_in, false)
      {:error, _} ->
        conn
        |> assign(:user_signed_in, false)
    end
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CookieAuthWeb do
    pipe_through [:browser, :check_auth, :req_auth]
    delete "logout", CookieController, :delete
    get "sessions", CookieController, :index
    delete "sessions/delete/:id", CookieController, :delete_session
    resources "users", UserController, only: [:delete]
  end

  scope "/", CookieAuthWeb do
    pipe_through [:browser, :check_auth, :req_no_auth]
    get "login", CookieController, :new
    post "login", CookieController, :create
    resources "users", UserController, only: [:new, :create]
  end

  scope "/", CookieAuthWeb do
    pipe_through [:browser, :check_auth]

    get "/", PageController, :index
    resources "users", UserController, only: [:index]
  end

  # Other scopes may use custom stacks.
  # scope "/api", CookieAuthWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: CookieAuthWeb.Telemetry
    end
  end
end

lib/cookie_auth_web/views/layout_view.ex
defmodule CookieAuthWeb.LayoutView do
  use CookieAuthWeb, :view
end

lib/cookie_auth_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>CookieAuth · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
      <%= link "Listing Users", to: Routes.user_path(@conn, :index) %><br>
      <%= if CookieAuth.Accounts.user_signed_in?(@conn) do %>
        You're Logged In As <%= @conn.assigns.current_user.email %> 
        <%= link "Logout", to: Routes.cookie_path(@conn, :delete), method: :delete %><br>
        <%= link "Manage Your Available Sessions", to: Routes.cookie_path(@conn, :index) %>
      <% else %>
        <%= link "Login", to: Routes.cookie_path(@conn, :new) %>
      <% end %>
      <br>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>